services:
    
    postgresql:
        image: postgres:17
        container_name: postgresql
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            TZ: Europe/Budapest
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        shm_size: 2g
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/postgresql.conf:/var/lib/postgresql/postgresql.conf
            - ./postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        command: postgres -c config_file=/var/lib/postgresql/postgresql.conf
        restart: unless-stopped
        networks:
            - training

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
          - "5050:80"
        networks:
             - training
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        ports:
            - "${PROMETHEUS_PORT:-9090}:9090"
        restart: unless-stopped
        networks:
             - training

    grafana:
        image: grafana/grafana
        container_name: grafana
        environment:
            GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
            GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
        volumes:
            - grafana:/var/lib/grafana
        ports:
            - "${GRAFANA_PORT:-3000}:3000"
        restart: unless-stopped
        networks:
            - training

    postgresql-exporter:
        image: prometheuscommunity/postgres-exporter:latest
        container_name: postgresql-exporter
        ports:
            - "9187:9187"
        environment:
            DATA_SOURCE_NAME: "postgresql://postgres:${DB_PASSWORD:-secret}@postgresql:5432/postgres?sslmode=disable"
        depends_on:
            prometheus:
                condition: service_started
            postgresql:
                condition: service_healthy
        restart: unless-stopped
        networks:
            - training
             
    zabbix-server:
      image: zabbix/zabbix-server-pgsql:ubuntu-latest
      container_name: zabbix-server
      restart: unless-stopped
      environment:
        DB_SERVER_HOST: postgresql
        POSTGRES_USER: ${ZABBIX_DB_USER}
        POSTGRES_PASSWORD: ${ZABBIX_DB_PASSWORD}
        POSTGRES_DB: ${ZABBIX_DB_NAME}
        ZBX_HISTORYSTORAGETYPES: log,text
        ZBX_DEBUGLEVEL: 1
        ZBX_HOUSEKEEPINGFREQUENCY: 1
        ZBX_MAXHOUSEKEEPERDELETE: 5000
      depends_on:
          postgresql:
              condition: service_healthy
      volumes:
        - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      networks:
        - training
    
    zabbix-web:
      image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
      container_name: zabbix-web
      restart: unless-stopped
      environment:  
        DB_SERVER_HOST: postgresql
        POSTGRES_USER: ${ZABBIX_DB_USER}
        POSTGRES_PASSWORD: ${ZABBIX_DB_PASSWORD}
        POSTGRES_DB: ${ZABBIX_DB_NAME}
        ZBX_SERVER_HOST: zabbix-server
        ZBX_POSTMAXSIZE: 64M
        ZBX_MAXEXECUTIONTIME: 500
      depends_on:
        zabbix-server:
          condition: service_started
        postgresql:
          condition: service_healthy
      ports:
        - 8090:8080
      networks:
        - training

    zabbix-agent:   
      image: zabbix/zabbix-agent2:ubuntu-latest
      container_name: zabbix-agent
      privileged: true
      restart: unless-stopped
      environment:
        ZBX_HOSTNAME: zabbix-agent
        ZBX_SERVER_HOST: zabbix-server
        ZBX_DEBUGLEVEL: 5
      networks:
        - training

volumes:
    postgresql:
    prometheus:
    grafana:
    postgresql-exporter:
    zabbix-server:
    zabbix-web:
    zabbix-agent:

networks:
    training:
        driver: bridge
